name: flutter_pos

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: any
  intl: any
  flutter_switch: any
  flutter_riverpod: any
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  uuid: any
  flutter_spinkit: ^5.2.0
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0
  equatable: ^2.0.5
  device_info_plus: ^11.0.0
  connectivity_plus: ^4.0.0
  hive: any
  hive_flutter: any
  path_provider: ^2.0.15
  workmanager:  ^0.9.0+3
  blue_thermal_printer: ^1.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
